### ISSUE TITLE
store.subscribe

### ISSUE THREAD

**Issue by zebapy** [reduxjs/redux-mock-store#1]
Would it be helpful to add store.subscribe method? 

I'm just getting started learning how to test react, so I'm not sure what it'd look like. I may be understanding this as intended to use for a completely different purpose than I'm trying to test. 

I'm trying to do this:

```
// I have a shallowRender helper util
const component = shallowRender(
        <Provider store={store}>
          <ConnectedCounterContainer />
        </Provider>
      )
```

so I can simply test to see if the component received the prop `count: 0` 

but I get:

```
Warning: Failed Context Types: Required child context `store.subscribe` was not specified in `Provider`.
```

so I'm assuming it wants a `store.subscribe()` method on the mocked store.

**Comment by arnaudbenard** [comment]
Does it make your test fail? If it's a warning you should be alright.

Can you send me a repo with the code so I can reproduce the warning message and try to fix it?

Thanks for the feedback.

**Comment by gaearon** [comment]
Why not use a normal store for testing components?
Redux Mock Store is intended to test async action creators and middleware.

**Comment by zebapy** [comment]
Sorry I'm pretty new to testing and realized this mock store's purpose (what @gaearon said) after I posted. Might be good to say ~~"A mock store for your testing your redux app"~~ "A mock store for your testing your redux async action creators and middleware", granted most people should understand this vs me who didn't because I'm a newb :smiley: 

@gaearon Are you saying create a mock "normal" store or use your apps configureStore you create? This is where I ended up coming across this.

**Comment by gaearon** [comment]
> Are you saying create a mock "normal" store or use your apps configureStore you create? This is where I ended up coming across this.

Yes. Please refer to the tests in Redux repo examples (e.g. `examples/counter`, `examples/todomvc`) to see how to test different parts of the app.

**Comment by gaearon** [comment]
The reason you'd mock the store is to assert that particular actions were dispatched without actually running the reducer or rendering the components. So this is why it's useful for async action creators. For all “real” test purposes you want to run the reducer, so in this case you'd use the real store.

**Comment by arnaudbenard** [comment]
@gaearon Thank you for the explanation. I will put a better description in the readme, it will help the next developers :)
