### ISSUE TITLE
Clean up tests

### ISSUE THREAD

**Issue by newyork-anthonyng** [reduxjs/redux-mock-store#100]
I was taking a look at the unit tests for `redux-mock-store` and came upon this [line](https://github.com/arnaudbenard/redux-mock-store/blob/master/test/index.js#L14).

```js
const store = mockStore(getState, [])
```

Is there a reason we are passing in an empty array as the second argument to `mockStore()`? Is this part of legacy code where `mockStore` used to take more arguments?

Let me know. I can make a PR to clean this up 👍

**Comment by dmitry-zaets** [comment]
Thanks a lot for opening issue and pointing out.
You are right, it's not needed. Feel free to open the PR.

**Comment by newyork-anthonyng** [comment]
@dmitry-zaets No problem. 

I created a [PR](https://github.com/arnaudbenard/redux-mock-store/pull/101). Let me know if anything else is needed. 👍
