### ISSUE TITLE
Dispatch within FileReader's reader.onload()

### ISSUE THREAD

**Issue by ghost** [reduxjs/redux-mock-store#103]
It seems that `mockedStore.getActions()` does not see dispatches within FileReader's `reader.onload()`
`mockedStore.getActions()` returns `[ { type: 'Works' } ]`
Can I get some help retrieving dispatches when using FileReader?
```javascript
export const importRule = file => dispatch => {
    const reader = new FileReader();
    dispatch({
        type: 'Works'
    });
    reader.onload = (e) => {
        dispatch({
            type: 'Does not work'
        });
    };
    reader.readAsText(file)
};
```

**Comment by toan2406** [comment]
@miguel-orange Hi, it depends on where you call `mockedStore.getActions()`. If it's called inside `onload`, it will have both 2 actions; if it's outside, will only have one `{ type: 'Works' }` because `onload` is async

**Comment by dmitry-zaets** [comment]
You can wrap onload into the promise, that will allow you to call getActions after onload gets finished
