### ISSUE TITLE
Dispatch missed inside map function of lodash library

### ISSUE THREAD

**Issue by SandeshBG** [reduxjs/redux-mock-store#105]
I have problem with testing async action creator using jest and I am using redux-mock-store to implement the mock store. The action creator uses instance of axios to fetch the data. The response data is in array, which I pass to map function.For each data in array it requests data from api and dispatches it to store. While testing I am able to detect all the dispatches except inside lodash library map function.
```js
//This is how my code looks
function actioncreator( ){
return function(dispatch){
      dispatch(types.loading_model);
     auth.get('model')//instance of axios requesting data from api
     .then(function(response){
        dispatch(types.get_model,response.data);
         dispatch(types.loading_media);
        _.map(response.data.data,(newData,Index)=>{
              auth.get('media',{
              params:{id:newData.id}})
          .then(function(response){
            dispatch(types.get_media,response.data);
          })
     })
}
```
```js
//This is my test for action creator
it('action creator test',() => {
const mockStore = configureMockStore([thunk]);//from redux-thunk
const store = mockStore({data:[]});
return store.dispatch(actioncreator()).
then(() => {
    expect(store.getActions().length).toBeGreaterThanOrEqual(4);//this will be always 3 in test
})
})

```
The dispatch inside lodash map is missed in test. I can see the response data inside the function. But the mockstore dispatch is missing those dispatch.

**Comment by newyork-anthonyng** [comment]
@SandeshBG I think the issue is that your promises haven't all resolved yet when you do your `expect` statement.

Does changing your source code like this help?
```js
function actioncreator( ){
  return function(dispatch){
    dispatch(types.loading_model);
    // notice the "return" statement here
    return auth.get('model') //instance of axios requesting data from api
    .then(function(response){
      dispatch(types.get_model,response.data);
      dispatch(types.loading_media);
  
      // notice the "return" statement here
      // I am using Promise.all to wait for our array of Responses to resolve    
      return Promise.all(_.map(response.data.data,(newData,Index)=>{
        return auth.get('media',{
          params:{id:newData.id}})
          .then(function(response){
            dispatch(types.get_media,response.data);
          })
        })
      }
    }
  }
```

**Comment by SandeshBG** [comment]
Yes it worked. I have another issue similar one. What should I do if I have multiple axios requests and responses inside main .then( ). I cannot have multiple returns on the same function!

**Comment by newyork-anthonyng** [comment]
@SandeshBG Are your axios requests running in `parallel`? Or one after another, `serially`?

If they are running in `parallel`, one way you can handle it is using `Promise.all`. It returns one promise that resolves when all of its promise arguments have resolved. Check out the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).

If they are running `serially`, you can chain your Promises together. It would look something like this:
```js
return axios.get('/firstRequest')
  .then(firstResponse => {
    // I can use the results of my first response here
    return axios.get('/secondRequest');
  })
  .then(secondResponse => {
    // I can use the results of my second response here
    return axios.get('/thirdRequest');
  })
  // etc.
```

Let me know if you have any questions about it.

**Comment by SandeshBG** [comment]
Can I use Promise.all for parallelly running axios requests,even if there are dispatches in the middle that does nothing but the state change of redux-store(just like the first dispatch of my actions creators)?

**Comment by dmitry-zaets** [comment]
You have two options, you can use Promise.all to get a promise that will be resolved after all nested promises would be resolved, or you can use chaining as @newyork-anthonyng proposed.
Actually, you can take a look on [redux-actions-assertions](https://github.com/redux-things/redux-actions-assertions) which could simplify your testing workflow. We have created that library to simplify the cases similar to yours.

**Comment by SandeshBG** [comment]
@dmitry-zaets Thanks. I will look into redux-actions-assertions as you suggested
