### ISSUE TITLE
Usage with JSDOM 

### ISSUE THREAD

**Issue by alexwong98** [reduxjs/redux-mock-store#106]
When using this (https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md) to setup my global document / window for my test environment for enzyme, there seems to be an error when using it in conjunction with `configureMockStore`; 

I am getting this error:
`     Invariant Violation: _registerComponent(...): Target container is not a DOM element.
`
What is the cause of this? I don't see how configureMockStore should be affected by the JSDOM configurations before the tests.

**Comment by newyork-anthonyng** [comment]
@alexwong98 I'm not sure why `configureMockStore` would be causing that error.

Could you create a repository that reproduces this issue?

**Comment by dmitry-zaets** [comment]
Please provide an example, so we can try to locate the problem.

**Comment by alexwong98** [comment]
Sorry, it was an unrelated issue. Thank you.
