### ISSUE TITLE
UMD Build

### ISSUE THREAD

**Issue by jongunter** [reduxjs/redux-mock-store#107]
Some devs (like myself) want to use this library in an  environment without a module loader/bundler (where all libraries are globally available on the `window` object). A UMD build would be helpful here.

**Comment by dmitry-zaets** [comment]
Related to #90

**Comment by arnaudbenard** [comment]
I'm not familiar with UMD, you are welcome to make a PR for that.

**Comment by dmitry-zaets** [comment]
@jongunter can you please test build of this pr? https://github.com/arnaudbenard/redux-mock-store/pull/108
