### ISSUE TITLE
unable to test in isolation async actions with jest

### ISSUE THREAD

**Issue by mgenov** [reduxjs/redux-mock-store#110]
I'm encountering an issue (either on jest or in the redux-mock-store) which forces test to not be isolated between calls. 

I've created a sample project to illustrate the issue. This is the test code: 
https://github.com/mgenov/test-middleware-with-jest/blob/master/src/axiosMiddleware.spec.js

When just one of the test is executed it passes but when whole suite is executed then one of them fails as it keeps the state of the previous test. 

Running one test
<img width="520" alt="screen shot 2017-08-17 at 2 03 28 pm" src="https://user-images.githubusercontent.com/209223/29409442-dfc1799c-8354-11e7-84fd-3ad1751521e6.png">

Running both
<img width="547" alt="screen shot 2017-08-17 at 2 02 54 pm" src="https://user-images.githubusercontent.com/209223/29409428-ce141844-8354-11e7-87a3-88347f014d11.png">

**Comment by newyork-anthonyng** [comment]
@mgenov Hmm, this is an interesting bug.

Looking at your code, if I add a `console.log` here:
```js
const store = mockStore({ access_token: '::another_access_token::' })
console.log(store.getState()) // { access_token: '::another_access_token::' }
```

However, adding a `console.log` [here](https://github.com/mgenov/test-middleware-with-jest/blob/master/src/axiosMiddleware.spec.js#L11) shows me the wrong `getState`. I'm going to do some more investigating when I have time.

**Comment by mgenov** [comment]
Thanks @newyork-anthonyng. 

I've encountered similar issue and with actions (kept actions from previous test) and will try to simulated in this project too.

**Comment by newyork-anthonyng** [comment]
I added a `uid` inside of the `redux-mock-store` code.

```js
// node_modules/redux-mock-store/lib/index.js

// ...some code
return function mockStore() {
    var _getState = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
    var uid = Math.random(); // note this addition

    function mockStoreWithoutMiddleware() {
      var actions = [];
      var listeners = [];

      var self = {
        getState: function getState() {
          console.log(uid);  // note this addition
          return isFunction(_getState) ? _getState() : _getState;
        },
// ...some more code
```

I ran this test code with a simple redux middleware:
```js
const myMiddleware = store => next => action => {
  console.log(store.getState());
  next(action);
};
const mockStore = configureMockStore([myMiddleware]);

it('first test', () => {
  const store = mockStore({ foo: 'bar' });
  console.log(store.getState());
});

it('second test', () => {
  const store = mockStore({ foo: 'baz' });
  console.log(store.getState());
})
```

I looked at my output and saw two different random numbers being outputted. This means that there are 2 different stores being used by my custom middleware. This makes sense 👍 

@mgenov When I ran your tests, I saw that I was seeing the same number being output. This makes me suspect that `redux-mock-store` might not be to blame.

Is it possible that `redux-axios-middleware` is somehow caching the first redux store that it uses? I'm not too familiar with its internals.

**Comment by mgenov** [comment]
It looks like that it's not cached. I wrote this test in test/middleware.js of redux-axios-middleware and it passes as expected.

Here is the test code:
```javascript
  it('should check state', () => {
    mockAxiosClient.onGet('/test').reply(200);
    const action = {
      type: 'LOAD',
      payload: {
        request: {
          url: 'test',
          adapter: mockAdapter
        }
      }
    };
    const store = mockStore({ myState: true });
    console.log(store.getState()); // outputs: myState: true
    return store.dispatch(action).then(() => {
      expect(store.getState()).to.shallowDeepEqual({ myState: true });
    });
  });

  it('should check another state', () => {
    mockAxiosClient.onGet('/test').reply(200);
    const action = {
      type: 'LOAD',
      payload: {
        request: {
          url: 'test',
          adapter: mockAdapter
        }
      }
    };
    const store = mockStore({ myState: false });
    console.log(store.getState());  // outputs: myState: false
    return store.dispatch(action).then(() => {
      expect(store.getState()).to.shallowDeepEqual({ myState: false });
    });
  });
```

I suppose the problem is somewhere else.

**Comment by mgenov** [comment]
Confirmed that it's caused from the redux-axios-middleware. It caches adding of interceptors by using the name of the client and the injection of getState and dispatch is permanent for the client. 

As test is not creating a new client it uses the getState() function call of the first store that was passed in.

Thanks for your feedback.

**Comment by dmitry-zaets** [comment]
thanks @newyork-anthonyng for helping out!
