### ISSUE TITLE
Is anyone else getting an old version on npm?

### ISSUE THREAD

**Issue by tendolukwago** [reduxjs/redux-mock-store#111]
The version I'm grabbing from npm (@1.2.3) does not look the same as the version in this github repo (@1.2.3). For example, the code in this repo is written using ecma6, but the copy i keep getting from npm isn't. Any idea on why this may be happening?

**Comment by newyork-anthonyng** [comment]
Hi @tendolukwago 

Good question. What does the code you are downloading from `npm` look like?
Do the first couple of lines look something like the below:
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = configureStore;
```

If it is, then everything is good 👍 
The version that you are downloading is what the code looks like after going through [babel](http://babeljs.io/).

**Comment by tendolukwago** [comment]
Dope. Thanks for the quick reply. 

I'm having another problem I'm hoping you can help me on. Gonna open up another issue.
