### ISSUE TITLE
arguments incompatible with signature in test/index.js

### ISSUE THREAD

**Issue by ciekawy** [reduxjs/redux-mock-store#114]
test does not makes sense as in line https://github.com/arnaudbenard/redux-mock-store/blob/82aba88c2e9d74af49d0fff8b3aea55db6070e4a/test/index.js#L100

`mockStore` accepts just one argument so `expectedActions` wont't be modified anyway

**Comment by dmitry-zaets** [comment]
Thats a good spot! Thats a lot, we'll fix it!

**Comment by arnaudbenard** [comment]
@ciekawy You are looking at the tests of the old `redux-mock-store` where it used to accept an array of actions.

**Comment by ciekawy** [comment]
yea, I just noticed the same call in my project and was investigating the source of it :)
