### ISSUE TITLE
Cannot find module 'redux' from 'index.js'

### ISSUE THREAD

**Issue by JamesTheHacker** [reduxjs/redux-mock-store#117]
I'm getting an error that redux is missing. I can't quite figure out what's going on because redux is installed in my project.

```
FAIL  src/__test__/actions.test.js
  ● Test suite failed to run

    Cannot find module 'redux' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (../node_modules/redux-mock-store/lib/index.js:8:14)
```

**actions.test.js**

`const mockStore = require('redux-mock-store');`

It's failing on import.

I'm using Node 8.4.0, and mock-redux-store@1.3.0

**Comment by JamesTheHacker** [comment]
I removed `node_modules` and ran `npm i` and everything works.

**Comment by natural411** [comment]
> I removed `node_modules` and ran `npm i` and everything works.

tried that, no difference

**Comment by gabyvlad96** [comment]
What's the status on this?
Any fixes?

Edit:
Found the solution here: https://github.com/jest-community/vscode-jest/issues/382#issuecomment-424083512
