### ISSUE TITLE
No CommonJS version

### ISSUE THREAD

**Issue by sbason** [reduxjs/redux-mock-store#129]
A lot people will probably want to use this library in a node.js environment that does not support ES6 Modules yet. It would not be that much effort to transpile for those users.

**Comment by sbason** [comment]
Just seen related to https://github.com/arnaudbenard/redux-mock-store/issues/90 and https://github.com/arnaudbenard/redux-mock-store/pull/108. Can we please get the solution merged ASAP please?

**Comment by arnaudbenard** [comment]
@sbason Commented here https://github.com/arnaudbenard/redux-mock-store/issues/90#issuecomment-359911880

**Comment by dmitry-zaets** [comment]
Closed by #132
