### ISSUE TITLE
Fix grammar in repo description

### ISSUE THREAD

**Issue by dharkness** [reduxjs/redux-mock-store#130]
Remove the first "your" in the repo's description, and consider removing both.

> A mock store for **your** testing your redux async action creators and middleware

Bonus points: capitalize Redux. :)

**Comment by dmitry-zaets** [comment]
Thanks a lot for the contribution!

**Comment by dharkness** [comment]
It's also in the repo description. There's an **Edit** button to the right of it at the top of the home page.

**Comment by dmitry-zaets** [comment]
Thanks, fixed
