### ISSUE TITLE
Cannot import redux-mock-store with v1.5.0

### ISSUE THREAD

**Issue by Guymestef** [reduxjs/redux-mock-store#133]
Hello,

I upgraded redux-mock-store from v1.4.0 to v1.5.0, and with the new version I get:
TypeError: redux_mock_store_1.default is not a function

No code change on my project except the upgrade to v1.5.0...

Sample use in my project:
```Typescript
import createMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import ApiService from 'services/ApiService';

const middlewares = [thunk.withExtraArgument({ apiService: ApiService })];
const mockStore = createMockStore<any>(middlewares);
```

**Comment by dmitry-zaets** [comment]
@sbason, any ideas on that?

**Comment by sbason** [comment]
@Guymestef how are you transpiling your code from ES6? It's likely because in 1.5.0 we're now exporting the commonJS as `main` and the ES6 module as `module` in `package.json` and your build system is looking at the commonJS version and cannot understand it. This version should probably have been a breaking change.

**Comment by dmitry-zaets** [comment]
@sbason well, ES6 should be a default one, and the CommonJS should be by path - in that case, it would not be a breaking change.
Can you refactor that part to keep the backward compatibility?

**Comment by sbason** [comment]
@dmitry-zaets Well the NPM guidelines suggest that `pkg.main` should be CommonJS or UMD and ES6 modules should be `pkg.module` and/or `pkg.js:next` so I think this is bringing the package into generally accepted standards. 

But I've just noticed invesitgated and this is not actually the issue. I'm not sure how the ES6 module is being generated but it looks like after `npm publish` it ends up in the `lib/index.js`  directory and the `pkg.module` is currently pointing at `src/index.js`. I'll open a PR to fix this.

**Comment by sbason** [comment]
@dmitry-zaets I've figured out how it got built. Looks like the npm script that did it went missing in our PR. I've raised https://github.com/arnaudbenard/redux-mock-store/pull/134 to add it back in to fix this.

**Comment by dmitry-zaets** [comment]
@sbason Thanks a lot!
Would be nice to also add docs with "how to use both ways"

**Comment by dmitry-zaets** [comment]
Would be fixed with 1.5.1

**Comment by dbenchi** [comment]
I am now on 1.5.1 and I have the same issue. I have changed nothing in my tests. I only bumped the redux-mock-store from 1.4.0 to 1.5.1

IMHO, this issue is to be reopened

**Comment by sbason** [comment]
@abenchi can you give us some details on how to reproduce?

**Comment by dmitry-zaets** [comment]
I've just tried with redux-actions-assertions (which is using mock-store under the hood) and all tests are passing

**Comment by dbenchi** [comment]
```javascript
/// <reference types="jest"/>

import axios from 'axios';
import * as AxiosMockAdapter from 'axios-mock-adapter';
import createMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import { submitEmail } from './';

describe('submitEmail', () => {
  let store, axiosMockAdapter;

  beforeEach(() => {
    axiosMockAdapter = new AxiosMockAdapter(axios);
    store = createMockStore([thunk])({});
  });

  it('dispatches correctly',  async () => {
    axiosMockAdapter.onAny().reply(200);

    await store.dispatch(submitEmail('email'));
    
    expect(store.getActions()).toMatchSnapshot();
  });
});
```
I just updated bumped the redux-mock-store and all tests (like the aforementioned one) fail with the same message error `TypeError: redux_mock_store_1.default is not a function`
Once reverted to the version 1.4.0, every thing is working correctly.
Please feel free to ask me for the details you want that may help you debugging the isse

**Comment by banyan** [comment]
@sbason @dmitry-zaets 

I've created small repo (branch is `redux-mock-store-133`) to reproduce: https://github.com/banyan/issue-repro/tree/redux-mock-store-133
(1.4.0 works fine)

**Comment by Guymestef** [comment]
Hello,
Sorry for the late reply...
I just tested the 1.5.1, so now I see that we have different files for each type of module system, but I still get the same error.
I'm running my tests with jest and typescript is transpiling the files with the following conf:
```JSON
{
  "compilerOptions": {
    "baseUrl": "ClientApp/src",
    "module": "es6",
    "moduleResolution": "node",
    "target": "es6",
    "jsx": "react",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "strictNullChecks": false,
    "lib": ["es6", "dom"],
    "types": [
      "webpack-env",
      "node",
      "jest"
    ]
  },
  "exclude": [
      "bin",
      "node_modules"
  ],
  "files": [
    "./ClientApp/src/typings.d.ts"
  ],
  "include": [
    "./ClientApp/**/*"
  ]
}
```

**Comment by cscleison** [comment]
i'm having the same error as @abenchi

**Comment by sbason** [comment]
The discussion on this seems to have moved to https://github.com/arnaudbenard/redux-mock-store/issues/135 where they've nailed the bug. I have a PR to fix it here: https://github.com/arnaudbenard/redux-mock-store/pull/136. Hopefully it will get merged soon.

**Comment by nWidart** [comment]
I'm on `1.5.1` and still experiencing the issue.

Has this been fixed in the meantime. I see that PR #135 was merged, but maybe not tagged yet?

Thanks!

**Comment by erik-r-peterson** [comment]
This isn't working for me no matter the version in a codebase I created last week, though it works on an older project. I wonder if a change in typescript/ts-node is incompatible?

Old project which works:
ts-node: 3.3.0, typescript: 2.5.2, redux-mock-store: 1.2.3

New project which fails:
ts-node: 5.0.1, typescript: 2.6.2, redux-mock-store: 1.5.1 (I also tried 1.4.0 since it worked for @abenchi but that fails too for me and so does 1.2.3 in this setup)

**Comment by zone-live** [comment]
I also share the same problem as @DarthDerrr still getting the **redux_mock_store_1.default** error.
I've installed the redux-mock-store: 1.4.0, 1.5.1 but its all the same

typescript: 2.7.2,
redux-mock-store: 1.4.0,
types/redux-mock-store: 0.0.13

**Comment by nWidart** [comment]
@zone-live temporary workaround is to import it like so:

```js
const configureMockStore = require('redux-mock-store');
```

**Comment by zone-live** [comment]
It worked @nWidart :P but makes no sense to me... why this workaround?

**Comment by nWidart** [comment]
I have no idea too :D 

More info here https://github.com/arnaudbenard/redux-mock-store/issues/144#issuecomment-375298780

**Comment by marcucio** [comment]
This fixed it for me, changing:
```
import configureStore from 'redux-mock-store';
```
to
```
import * as configureStore from 'redux-mock-store';
```

**Comment by zone-live** [comment]
@marcucio It works as well, good one 👍

**Comment by chawax** [comment]
I had a similar problem (not exactly the same error message) when importing configureStore in Storybook stories after a React Native upgrade.

I could solve it by changing :

```
import configureStore from 'redux-mock-store'
```

to 

```
import configureStore from 'redux-mock-store/dist/index-umd'
```

**Comment by paulsturgess** [comment]
For what it's worth, I couldn't get either of the following to work 

```js
import * as configureStore from 'redux-mock-store';
import configureStore from "redux-mock-store";
```

- redux-mock-store: 1.5.1
- types/redux-mock-store: 0.0.13
- typescript 2.8.3

This was fine:
```js
const configureStore = require('redux-mock-store');
```

But for now I've reverted to `1.4.0` where this continues to work:

```js
import configureStore from "redux-mock-store";
```

**Comment by lucksp** [comment]
I have tried adding redux-mock-store v1.4 and v1.5.3 to try and fix the issue, but just by adding the imports or requires generates the error:

> Test suite failed to run
>     Cannot find module 'redux' from 'index.js'
> 
>       at Resolver.resolveModule (node_modules/jest-cli/node_modules/jest-resolve/build/index.js:221:17)
>       at Object.<anonymous> (../node_modules/redux-mock-store/lib/index.js:8:14)

Package.json:
```
devDeps:
   "babel-jest": "^23.4.0",
    "jest": "21.3.0-beta.2",
    "jest-cli": "^23.5.0",
     "redux-mock-store": "^1.5.3",
"jest": {
        "testMatch": [
            "**/__tests__/**/?(*.)(spec|test).js?(x)"
        ],
        "setupTestFrameworkScriptFile": "./__tests__/mocks/localStorageMock.js",
        "setupFiles": [
            "<rootDir>/__tests__/globals.js"
        ]
    }
```
Test file:
```
import configureStore from "redux-mock-store";
import thunk from "redux-thunk";

const middlewares = [thunk];
const mockStore = configureStore(middlewares);
```

I appreciate any suggestions.

**Comment by newyork-anthonyng** [comment]
@lucksp Can you create a basic example that reproduces this error? And share it on Github?

**Comment by lucksp** [comment]
@newyork-anthonyng like with my whole webpack config, npm scripts, and everything?

**Comment by newyork-anthonyng** [comment]
@lucksp You don't have to upload your entire project; just enough so that I can run the tests and see the `Cannot find module 'redux' from 'index.js'` error that you are seeing.

It'll be easier for others to debug.

**Comment by newyork-anthonyng** [comment]
@lucksp Can you upload this to a Github repository? And make sure that you are able to run `npm run test` yourself and that it shows the expected error?

I downloaded the files from your gist, but the files aren't configured correctly. For example, I'd have to reconstruct your entire directory structure for imports like `"../../src/redux/actions/ActionCreators/Chat"`. And files like `./__tests__/mocks/localStorageMock.js` are missing.

I'll be more than happy to look at it after you do that.

PS. I also find that reproducing your project uncovers where the errors really are.

**Comment by lucksp** [comment]
It was something with the package.json.  got it now.  THANKS
