### ISSUE TITLE
Breaking changes introduced in minor version

### ISSUE THREAD

**Issue by Jameskmonger** [reduxjs/redux-mock-store#135]
In `redux-mock-store@1.4.0`, the schema of the export is like this:

```
export = {
    default: function configureStore() { ... }
}
```

In `redux-mock-store@1.5.0`, the schema of the export is like this:

```
export = function configureStore() { ... }
```

The change between versions `1.4.0` and `1.5.0` is a **minor version** change. Breaking changes should **not** have been introduced in this version.

This package has almost 30k downloads per day, so to introduce breaking changes in a minor version has quite a large impact.

The best plan of action would be to mark version `1.5.0` and `1.5.1` as deprecated with:

```
npm deprecate redux-mock-store@1.5.0 "breaking changes in minor version"
npm deprecate redux-mock-store@1.5.1 "breaking changes in minor version"
```

and to republish the current version as `2.0.0`.

**Comment by hisuwh** [comment]
Why change this anyway?

**Comment by Jameskmonger** [comment]
@hisuwh 

> Why change this anyway?

I think this is due to #132, but that's not marked as a breaking change in the release notes...

**Comment by dmitry-zaets** [comment]
Sorry for the inconvenience.
I've deprecated both 1.5.0 and 1.5.1
We would test new version better to avoid breaking change or bugs.

**Comment by Jameskmonger** [comment]
It may be worth adding some unit tests around importing (probably more of an integration test), but something like this:

```
Expect(reduxMockStore)
    .toBeAFunction()
    .withName("configureStore");

Expect(reduxMockStore.default)
    .toBeAFunction()
    .withName("configureStore");
```

(pseudocode)

**Comment by csi-lk** [comment]
Hmm, I've got my build failing as this dependency is now deprecated, as far as I can tell there is no upgrade target?

Would be good it could be republished at `2.0.0` as @Jameskmonger suggested

**Comment by alasdairhurst** [comment]
Not really much point releasing a 2.0.0 if the breaking change was unintentional/unnecessary. This issue at the moment anyone will still pick up the deprecated version with breaking changes as latest, so a minor/patch version which reverts the breaking change should ideally be released as latest so anyone depending on ^ will pick it up without problems.

**Comment by reesscot** [comment]
Agree with @alasdairhurst on this one, @dmitry-zaets can we please get the change reverted and republished as the next minor release number, 1.6.0 or patch version 1.5.2? Still getting deprecated messages in NPM.

**Comment by Jameskmonger** [comment]
It should be released as a patch version ideally as it is patching a break.

**Comment by thomashagstrom** [comment]
Do mind the TypeScript mappings (`@typings/redux-mock-store`), that need to be synced with these changes.

**Comment by innerdaze** [comment]
Did this ever happen? It's now April

**Comment by dmitry-zaets** [comment]
Sorry for the late response and the inconvenience caused by the breaking changes that we introduced.
We didn't expect that it would actually cause the breaking change.
Version 1.4.0. was republished as 1.5.3 in order to fix the mess around the breaking changes.

**Comment by mrichmond** [comment]
Thank you... a bit concerning that it took 5 months to release the patch though...
