### ISSUE TITLE
Lib folder not downloading

### ISSUE THREAD

**Issue by pavankumargooty** [reduxjs/redux-mock-store#137]
Hi,

I am unable to view the lib folder after i tried installing npm packages on the build server. I am able to see the lib folder locally , but not on the build server.

**Comment by Floriferous** [comment]
Had the same issue, revert to `1.4.0` to fix it. `1.5.*` is having issues as mentioned in #135.

**Comment by pavankumargooty** [comment]
Sure thanks for the response

**Comment by dmitry-zaets** [comment]
We've deprecated all `1.5.*` versions because of issues with the build of es6 version. Please use `1.4.0`.
Sorry for the inconvenience.

**Comment by dmitry-zaets** [comment]
Fixed, see comments in #135
