### ISSUE TITLE
Can not set the initial state of the store

### ISSUE THREAD

**Issue by octaviantu** [reduxjs/redux-mock-store#139]
I have the following code:

> import configureMockStore from 'redux-mock-store';
> 
> const initialState = { someField: {} };
> const mockStore = configureMockStore();
> store = mockStore(initialState);
> console.log("Store is: " + JSON.stringify(store));

The `console.log` prints:

>       Store is: {}

Why doesn't `someField` appear when printing the store?

Am I not initialising it properly?

**Comment by newyork-anthonyng** [comment]
@octaviantuchila14 Could you update your code to call `store.getState()`? Does that fix your issue?

**Comment by octaviantu** [comment]
You're right, I wasn't printing correctly.
