### ISSUE TITLE
getActionsByType ?

### ISSUE THREAD

**Issue by stubar** [reduxjs/redux-mock-store#142]
I find in most test cases that I am doing a filter on getActions to make test a bit more specific.  It would be handy to have a getActionsByType helper in the api so we could do a test like 

```
expect(store.getActionsByType('modal/TOGGLE_MODAL_DIALOG')).toHaveLength(1)
```

Happy to raise a PR

**Comment by acostalima** [comment]
You can easily look-up an action by type with [.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) and then assert the result.

**Comment by dmitry-zaets** [comment]
Agree with @acostalima 
Also, you can take a look into https://redux-things.github.io/redux-actions-assertions
