### ISSUE TITLE
redux_mock_store_1.default is not a function

### ISSUE THREAD

**Issue by nWidart** [reduxjs/redux-mock-store#144]
Hello,

I'm having the following error:

```
redux_mock_store_1.default is not a function
```

I first thought it was related to the upgrade to 1.5.1, however when reverting back to 1.4.0 the issue remains.

I'm not sure what I'm missing. I'm following the docs with my setup:

```js
import configureStore, { MockStore } from 'redux-mock-store';
import thunk from 'redux-thunk';

const mockStore = configureStore([thunk]);

function createFilledStore(): MockStore<State> {
  const initialState = {
    react_auth__authentication: {
      user: FAKE_USER,
    },
  };

  return mockStore(initialState);
}
```

This is a typescript version, using ` @types/redux-mock-store@0.0.13`

Thanks,

**Comment by jose920405** [comment]
try

`import * as configureMockStore from 'redux-mock-store';`

**Comment by nWidart** [comment]
Hello,

That gives me the following:

![image](https://user-images.githubusercontent.com/882397/37771166-0ff2f690-2dd7-11e8-857c-d2df9ad610ab.png)

**Comment by jose920405** [comment]
Yes, i'm presenting the same error.

Let me looking that.

But for now, my test are running. :)

**Comment by nWidart** [comment]
Oh you're right! The tests are back to green, not crashing on that typescript/phpstorm is reporting.

**Comment by jose920405** [comment]
@nWidart 

Are you found any solution for this warning?

I just found that using `require` instead `import` can fix the problem, but i think that is a wrong way: 

`const configureMockStore = require('redux-mock-store'); // Prevent Ts warning`.

**Comment by nWidart** [comment]
I haven't, no.
Indeed, `require` does 'hide' the warning from typescript.

Might be related to https://github.com/arnaudbenard/redux-mock-store/pull/136, https://github.com/arnaudbenard/redux-mock-store/issues/133

**Comment by tjaskula** [comment]
I have the same issue with typescript. Workaround `const configureMockStore = require('redux-mock-store');` does the job but it feels wrong.

**Comment by seweren** [comment]
It seems somehow the distributed index-cjs.js file ends with `module.exports=configureStore` instead of typescript import compatible `exports.default=configureStore`. Strange that cloned and manually builded repo dist file is ok, and using `"build:cjs": "cross-env BABEL_ENV=es NODE_ENV=production rollup -f cjs -c -i src/index.js -o dist/index-cjs.js",` ends with the latter one.

**Comment by FDiskas** [comment]
version "1.3.0" and "1.4.0" does not have such error
https://unpkg.com/redux-mock-store@1.4.0/lib/index.js

**Comment by dmitry-zaets** [comment]
The version 1.4.0 was republished as 1.5.3 in order to fix the problem caused by breaking changes.
