### ISSUE TITLE
Add fake subscribe method

### ISSUE THREAD

**Issue by ngerritsen** [reduxjs/redux-mock-store#15]
Is it an idea to add a fake subscribe method so that you can use the store to test react-redux connectors? It doesn't even have to do anything by itself, you might be allowed to pass in your own spy or fake method.

**Comment by arnaudbenard** [comment]
Could you elaborate on the use case of this functionality? I haven't used the subscribe method yet and I'm curious about it.

**Comment by cengageLucas** [comment]
I'm trying to test a component that uses react-redux connect to map state to props. When I use redux-mock-store to provide a mocked store for a shallow or static markup render, it works fine and I can test. When I use the same mock store for a ReactTestUtils.renderIntoDocument, I get a TypeError of 'TypeError: 'undefined' is not a function (evaluating 'this.store.subscribe(this.handleChange.bind(this))')'.

@ngerritsen, do you think this is a case of what you're talking about? I'm looking for a way to provide what's missing but I'm not really sure how.

**Comment by bencripps** [comment]
I don't run into any errors, but I get warns if I don't add a fake method to my `mockstore` instance.

```
const store = configureStore([]);
const mockStore = store({}, {});
mockStore.subscribe = () => {};
```

**Comment by arnaudbenard** [comment]
Done in the new version! :+1:
