### ISSUE TITLE
Dispatching reducer action from simulate method

### ISSUE THREAD

**Issue by Quadriphobs1** [reduxjs/redux-mock-store#154]
I am trying to change value of redux state from when an input value is changed using the `simulate()` method but action keep running but the state is not changed from the reducer meaning the reducer is even touched at all.

```
...
const mockStore = configureStore([
  thunk
])
...
const initialState = {
      loading: false,
      name: '',
      email: '',
      message: '',
      submitted: false
    }
store = mockStore(initialState)
wrapper = shallow(<Form store={store}  />).dive()
wrapper.find('input.name-input').simulate('change', {target: {value: 'Quadri'}})
expect(inputState.name).toEqual('Quadri')
```
It keeps returning the empty string.

In my action I have 
```
export function updateName(value) {
console.log(value)
  return { type: UPDATE_NAME, value }
}
```

and the value is returning `Quadri` but from the reducer it's not triggering the reducer at all

**Comment by acostalima** [comment]
`redux-mock-store` does not support reducers. From the docs: 

> Please note that this library is designed to test the action-related logic, not the reducer-related one. In other words, it does not update the Redux store.
