### ISSUE TITLE
Tests not failing when expectations are not met

### ISSUE THREAD

**Issue by jdmunro** [reduxjs/redux-mock-store#16]
If I set up a test that _should_ fail because the dispatched actions do not meet the expectations, the test is in-fact passing which can be quite dangerous.

This is using redux-mock-store 0.0.6 and Jest 0.8.2.

I believe the problem lies here:

```
} catch (e) {
  if (done) {
    done(e);
  }
  throw e;
}
```

I was able to cause the test to fail as expected by simply not calling done, e.g:

```
} catch (e) {
  if (done) {
    //done(e);
  }
  throw e;
}
```

I'm not 100% sure if this is an issue with this library or one with Jest, therefore I have not put together a PR yet until the matter has been discussed.

**Comment by arizzitano** [comment]
I just noticed this too. Tests pass even if I pass junk into the `mockStore()` init call, e.g. `mockStore('asdf', done)`. Using redux-mock-store 0.0.6 with jasmine/karma and mocking XHRs with karma-jasmine-ajax.

**Comment by jwbennet** [comment]
I believe that this library supports Mocha instead of Jasmine and the two libraries differ on how they use the `done` function.  With Mocha, calling the done function with an error will fail the spec, but in Jasmine there is a special `done.fail` function which needs to be called to fail the spec ([see the docs for async support](http://jasmine.github.io/2.4/introduction.html#section-54)).  For now I'm working around it by passing in the done function like this:

```
const store = mockStore({ }, expectedActions, (e) => {
      if(e instanceof Error) {
        done.fail(e);
      } else {
        done(e);
      }
    });
```

**Comment by jdmunro** [comment]
Thanks @jwbennet your explanation makes complete sense, I'll use your workaround. I don't know if @arnaudbenard is interested in also supporting Jasmine. I can maybe put together a PR, if not feel free to close this issue.

**Comment by arizzitano** [comment]
@jwbennet thanks for the workaround!

@jdmunro @arnaudbenard +1 for Jasmine support (or a framework-agnostic fork).

**Comment by arnaudbenard** [comment]
Is there an easy method to detect if we are using Jasmine or mocha?

If that's the case, I'm happy to support Jasmine

**Comment by jdmunro** [comment]
I had a pragmatic solution in mind:

```
if (done.fail) {
    done.fail(e);
} else {
    // ... current exception handling.
}
```

It isn't the most robust solution but it should do the trick for now. Alternatively we can just look for the presence of the `jasmine` variable.

**Comment by erquhart** [comment]
I think the greater issue here is how redux-mock-store bypasses my assertion library. I've put a fair amount of time into integrating redux-mock-store into my tests, and I now feel strongly that this is an anti-pattern that will probably bite a lot of folks.

A mocking lib should not handle setting expectations. It should simply provide an interface that helps devs run isolated test scenarios. A mocking lib shouldn't need to support _any_ test framework - it's probably fair to say the issue of supporting mocha vs jasmine is an [xy problem](http://xyproblem.info/).

For now I'll be using spies when I need to mock around stores, but I do love the idea of using a lib like this - it just needs less responsibility. I guess we'll see if the guy who's actually doing something about this for the community agrees :)

At any rate, thanks for your work, mate.

**Comment by arnaudbenard** [comment]
I agree with @erquhart. The library should be framework agnostic. I have noticed that other people had problems with Jasmine and tape as well. I am not sure how to handle that yet. Do you have examples of libraries that have the same type of API?

**Comment by erquhart** [comment]
I've commented on #22.

**Comment by ghost** [comment]
Thanks for the workaround @jwbennet

**Comment by nikolasleblanc** [comment]
In the meantime, here's a temporary module for Jasmine (and Mocha): https://www.npmjs.com/package/redux-mock-store-jasmine

**Comment by arnaudbenard** [comment]
There's a new version out, please give it a try :facepunch:

**Comment by nikolasleblanc** [comment]
Excellent, thanks @arnaudbenard
