### ISSUE TITLE
Docs link is not working the NPM repo

### ISSUE THREAD

**Issue by shayc** [reduxjs/redux-mock-store#168]
Hey, just wanted to say the link for the docs in the NPM repo description is broken and redirects to a shady ads page.

https://www.npmjs.com/package/redux-mock-store

**Comment by JBallin** [comment]
This issue is still occurring.

Given that neither @dmitry-zaets nor @arnaudbenard has responded to this issue, I filed a ticket with npm directly. I'll update here if/when I get a response.

**Comment by shayc** [comment]
@JBallin nice I didn't know you can do that.. I guess it poses some security risk.

**Comment by dmitry-zaets** [comment]
Fixed, thanks.
Sorry for the late response
