### ISSUE TITLE
Can't test for no action dispatched?

### ISSUE THREAD

**Issue by VincentHoang** [reduxjs/redux-mock-store#17]
Is there a way to test that there are no actions? My function may have a condition before dispatching the action.

```
it('dispatches no actions', (done) => {
    const store = mockStore({}, [], done);

    store.dispatch( 
        (dispatch) => {}
    );
});
```

This test fails with:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by jdmunro** [comment]
It's tricky, given the nature of asynchronous testing. I don't see how it would be possible since we cannot determine when the code you're testing has finished executing, unless you call done.

**Comment by bhritchie** [comment]
You could call `done` yourself after a brief timeout. Then if you do get an unexpected action, you'll get an error like `expected [whatever action] to equal undefined]`.

**Comment by arnaudbenard** [comment]
> My function may have a condition before dispatching the action.

You could export that function and directly test it instead.

**Comment by frantic1048** [comment]
I'm using same thought of @bhritchie under Jasmine, test like this:

``` javascript
it('should not dispatch any action', (done) => {
  // I write actions like this because of #12 Jasmine issue
  // https://github.com/arnaudbenard/redux-mock-store/issues/12#issuecomment-182067964
  const expectedActions = [
    act => expect(act).toEqual(jasmine.any(Object)),
  ];

  // pass `done.fail` to mockStore so that
  // any dispatched action will fail this case.
  const store = mockStore({}, expectedActions, done.fail);

  store.dispatch(myKawaiiAction());

  // if no action dispatched after a proper timeout,
  // then pass it.
  setTimeout(() => done(), 200);
});
```

**Comment by jdmunro** [comment]
Seems fair enough. The only thing that bugs me is the arbitrary timeout value. What is an appropriate time to wait?

**Comment by frantic1048** [comment]
New API in 1.0 works well, the problem solved :+1:
