### ISSUE TITLE
update url's in package.json to point to latest location

### ISSUE THREAD

**Issue by stvcisco** [reduxjs/redux-mock-store#171]
Currently package.json refers to `http://arnaudbenard.com/redux-mock-store/` but that url is problematic to get to.  The proper url seems to be `https://github.com/dmitry-zaets/redux-mock-store`

Can we get package.json fixed up so that the Documentation link on npmjs.org goes to the correct documentation?

**Comment by JBallin** [comment]
I don't see this link in the `package.json` (or anywhere in the repo for that matter).

I believe you're referring to the docs link on npm - in which case you can close this as it is a duplicate of #168.

**Comment by stvcisco** [comment]
Duplicate of #168
