### ISSUE TITLE
Publish v1.0.0 and adopt semver

### ISSUE THREAD

**Issue by cesarandreu** [reduxjs/redux-mock-store#19]
Limiting the version number to just the minor number is kinda awkward.

**Comment by arnaudbenard** [comment]
The library is not stable yet, there are still some issues to solve before publishing v1.

**Comment by fasterthanlime** [comment]
@arnaudbenard I recommend reading https://nodesource.com/blog/semver-tilde-and-caret/ all the way down to 'Recommendation'

I think I'm going to start migrating my packages to 1.x.y

**Comment by arnaudbenard** [comment]
@fasterthanlime Interesting read. I didn't know the rule about the caret.
