### ISSUE TITLE
done() is called in error case even when not provided

### ISSUE THREAD

**Issue by bhritchie** [reduxjs/redux-mock-store#2]
The mock store accepts either `undefined` or a function as the `done` parameter. It also checks for `done` before calling it in the `try` case. However it doesn't check in the `catch` case. So if you don't supply a function and you have an error, you will get a `done is not a function error`.

Very helpful library, by the way.

**Comment by arnaudbenard** [comment]
Thank you for the feedback. I will try to push a fix this week :+1:

**Comment by arnaudbenard** [comment]
It got fixed here https://github.com/arnaudbenard/redux-mock-store/pull/4

Download version `0.0.3` ;)
