### ISSUE TITLE
Example with tape

### ISSUE THREAD

**Issue by marr** [reduxjs/redux-mock-store#21]
Hi, I am trying to run this library with `tape` but having some trouble. Here is my gist: https://gist.github.com/marr/a3195dadb924a977a00a

I receive the following error when running the test:  ✖ test exited without ending

**Comment by marr** [comment]
This does pass but I imagine there is something I'm missing to avoid having to do `t.ok(1); t.end()`

```
import test from 'tape'
import configureMockStore from 'redux-mock-store'
import thunk from 'redux-thunk'
import { asyncFindUsers } from '../actions'
import { FIND_USERS } from '../constants'
import nock from 'nock'

test('should find concierge user', assert => {
  const middlewares = [ thunk ]
  const mockStore = configureMockStore(middlewares)

  const email = 'someone@somewhere.com'

  nock('https://api.something.com')
    .get(`/v1/account?country=US&email=${email}`)
    .reply(200, { data: { email } })

  const expectedActions = [{
    type: FIND_USERS,
    payload: [{
      email
    }]
  }]

  const store = mockStore({ users: [] }, expectedActions, () => {
    assert.ok(1)
    assert.end()
  })

  store.dispatch(asyncFindUsers(email))
});

test('after all', assert => {
  nock.cleanAll()
  assert.end()
})
```

**Comment by arnaudbenard** [comment]
I have noticed that some users have problems with Jasmine as well. I have only tried this library with Mocha. I think that those test runners don't exit the same way. I need to find a way to make the library test runner agnostic.
