### ISSUE TITLE
Expected actions not checked if nothing is dispatched in code under test

### ISSUE THREAD

**Issue by strom** [reduxjs/redux-mock-store#25]
If I am testing a function that is supposed to dispatch certain actions, and I somehow forgot to dispatch _any_ actions, redux-mock-store won't even bother checking the expected actions defined in `mockStore`.

**Comment by arnaudbenard** [comment]
Can you provide an example?

**Comment by arnaudbenard** [comment]
There's a new version out, please give it a try :facepunch:
