### ISSUE TITLE
Test run twice when an error is reported?

### ISSUE THREAD

**Issue by tleunen** [reduxjs/redux-mock-store#26]
For some reasons, when a test fails, it seems to be run twice (or at least it sends twice `done(e)`).

Moreover, the error is very hard to read. Would it be possible to improve the error?

**Comment by arnaudbenard** [comment]
Which framework are you using? Mocha?

**Comment by tleunen** [comment]
Yep it was with mocha

**Comment by arnaudbenard** [comment]
The previous version of `redux-mock-store` was a bit buggy. I have updated it it with a new syntax that is framework agnostic, you should give it a spin https://github.com/arnaudbenard/redux-mock-store/
