### ISSUE TITLE
An option to only compare the provided properties in expectedActions

### ISSUE THREAD

**Issue by marksteyn** [reduxjs/redux-mock-store#28]
I have an action creator which which updates a user, and then dispatches another action to display a notification. The notification displays for a few seconds and then disappears. To make this happen a private id is assigned to the action by the notification action creator.

In my test, I'd like to ensure that both the user update action and the notification action are triggered successfully.

In expectedActions I can add a notification action with the correct action type, with the message in the payload, but I can't provide the private notification id.  Because the action I provided doesn't match exactly (the provided action has no id), the test fails.

Ideally I'd like an option to make the equality test less strict, one that ensures that the all the properties of the object in expectedActions are present and equal in the actual action, and that any additional properties in the actual action are ignored.

So for the purpose of my test, I'd like the following to be considered equal:

Object in expectedActions:
`{
  type: types.NOTIFICATION,
  message: 'user updated'
}`

Actual action: 
`{
  type: types.NOTIFICATION,
  id: 616,
  message: 'user updated'
  ...any other properties
}`

I can understand if this goes against the spirit of the project, in which case I'd certainly appreciate any suggestions on how to handle my situation.

Thanks.

**Comment by apvilkko** [comment]
@marksteyn: I came across a similar issue, and I used the function type expected action. In your case this would be:

```
import {assert} from 'chai'; // or whatever assert lib you prefer
...
const expectedActions = [
      incoming => {
        assert.equal(incoming.type, types.NOTIFICATION);
        assert.equal(incoming.message, 'user updated');
      }
];
```

**Comment by marksteyn** [comment]
Thanks @apvilkko - I hadn't realised that was possible. That's perfect for what I need.

**Comment by arnaudbenard** [comment]
Glad it got solved. ;)

Btw, I am refactoring the library to make it framework agnostic, you can follow the discussion here
https://github.com/arnaudbenard/redux-mock-store/issues/22
