### ISSUE TITLE
done() not being called 

### ISSUE THREAD

**Issue by Onionz** [reduxjs/redux-mock-store#30]
I have 2 test cases and the second one will not pass and throw

>  Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Here is my code snippet:

```
    it('creates FETCH_TODOS_SUCCESS when fetching todos has been done', (done) => {
        const expectedActions = [
            {type: TodoConstants.GET_TODOS_REQUEST},
            {type: TodoConstants.GET_TODOS_SUCCESS, todos: [
                {
                    id: 1, text: 'todo1', isDone: false
                },
                {
                    id: 2, text: 'todo2', isDone: true
                }
            ]}
        ];

        const store = mockStore({todos: []}, expectedActions, done);
        store.dispatch(actions.fetchTodos());
    });

    it('post ADD_TODO_SUCCESS when add todo has been done', (done) => {
        const expectedActions = [
            {type: TodoConstants.ADD_TODO_REQUEST, text: 'todo3'},
            {type: TodoConstants.ADD_TODO_SUCCESS, todo: {
                id: 3, text: 'todo3', isDone: false
            }}
        ];

        const store = mockStore({todos: []}, expectedActions, done);
        store.dispatch(actions.addTodo('todo3'));
    });
```

I duplicated the 'get' test case, only the first 'get' test case can pass. 
then I removed the duplicate test case and put the 'post' test case in front of the 'get' test case, neither test case can pass.

My temporary solution is calling the done() function explicitly for each test case.

**Comment by tofuness** [comment]
Assuming you're running on the latest version.

``` javascript
import { expect } from 'chai';
// ...
const store = mockStore({todos: []});
store.dispatch(actions.fetchTodos());
expect(store.getActions()).to.eql(expectedActions);
```

**Comment by davidpelayo** [comment]
It also happened to me (with the [old version](https://github.com/arnaudbenard/redux-mock-store/blob/v0.0.6/README.md)), but it was actually my issue.

If you see, I was expecting to fetch an immutable structure (due we use a middleware which convert responses to immutable data), like follows:

``` javascript
function fetch() {
  return dispatch => {
    dispatch(basicActionCreator(types.fetch.start));
    return api.get(urls.myResourceExample)
      .then((response) => {
        dispatch(dataActionCreator(types.fetch.finish, response.get('myKeyExample')));
      }, (response) => {
        dispatch(errorActionCreator(types.fetch.fail, response));
      });
  };
}
```

However, while expecting actions, the response example I provided wasn't an immutable Map:

``` javascript
const response = [{ id: 0, name: 'Example 1' }];

beforeEach(() => {
  spyOn(api, 'get').andReturn(Promise.resolve(response));
});

afterEach(() => {
  expect.restoreSpies();
});

it(`should create action ${types.fetch.finish}`, (done) => {
  const expectedActions = [
    { type: types.fetch.start },
    { type: types.fetch.finish, data: response }
  ];

  const store = mockStore({}, expectedActions, done);
  store.dispatch(actions.fetch());
});
```

Producing the following error:

```
ERROR: 'Unhandled promise rejection', TypeError{line: 27, stack: '
run

flush'}
```

While resolving the promise, there is an unhandled exception trying to access to a key (because the action actually expects to have a Map as a response), producing the error above.

The solution was simple, just expecting the proper structure fixed my test:

``` javascript
const response = fromJS({ myExample: [{ id: 0, name: 'Example 1' }]});

beforeEach(() => {
  spyOn(api, 'get').andReturn(Promise.resolve(response));
});

afterEach(() => {
  expect.restoreSpies();
});

it(`should create action ${types.fetch.finish}`, (done) => {
  const expectedActions = [
    { type: types.fetch.start },
    { type: types.fetch.finish, data: response.get('myExample') }
  ];

  const store = mockStore({}, expectedActions, done);
  store.dispatch(actions.fetch());
});
```

UPDATE: Using the [old version](https://github.com/arnaudbenard/redux-mock-store/blob/v0.0.6/README.md)

**Comment by Onionz** [comment]
@tofuness I used redux-mock-store 0.0.6 and nock 7.4.0 for testing the async action creators which is recommended in redux website. So you recommend to use the newest version?

**Comment by arnaudbenard** [comment]
I have updated the latest version last night. I need to make a PR on redux website for the new version. I would recommend migrating to it because it is framework agnostic :)

**Comment by davidpelayo** [comment]
Checked and working with newest version. Thanks!

I think this issue can then be considered closed, right?

**Comment by Onionz** [comment]
I will start the new version. Problem solved :D. Thanks for helping.

**Comment by arnaudbenard** [comment]
That's awesome :+1:
