### ISSUE TITLE
No longer works with redux-thunk

### ISSUE THREAD

**Issue by skratchdot** [reduxjs/redux-mock-store#31]
The following test case doesn't work (and it should IMO).  I was able to test code like this in v0.6, but can't in the new v1.0.2

``` js
  it('should work with redux-thunk', (done) => {
    function success() {
      return {
        type: 'FETCH_DATA_SUCCESS'
      };
    }
    function asyncAction() {
      return dispatch => {
        setTimeout(() => {
          dispatch(success());
        }, 10);
      };
    }
    const middlewares = [thunk];
    const mockStore = configureMockStore(middlewares);
    const store = mockStore({});
    store.dispatch(asyncAction()).then(() => {
      expect(store.getActions()[0]).toEqual(success())
      done();
    });
  })
```

Thanks for this great library BTW!

**Comment by arnaudbenard** [comment]
`asyncAction` does not return a promise, you won't be able to use `.then`.

``` js
// working example
    function asyncAction() {
      return dispatch => {
        return Promise.resolve()
        .then(() => dispatch(success()));
      };
    }
```

**Comment by skratchdot** [comment]
I guess I knew that before posting :)  Are you planning on supporting redux-thunk usage (or do you have a simple test case w/ redux-thunk support)?  The old code would execute actions if they were functions, but the new code doesn't appear to: https://github.com/arnaudbenard/redux-mock-store/blob/0af25acf978bf109b9fbb4f497a93f6bc51eb0e2/src/index.js#L20-L24

The old code would check if an action was a function, then execute it: https://github.com/arnaudbenard/redux-mock-store/commit/14842c4423322cc438d0582473483b8caaf5b3a7#diff-1fdf421c05c1140f6d71444ea2b27638L27

But I'm not sure how that will work with your newer/simpler version...

I'll look around in the code a bit more.  Was just trying to convert from 0.6 to 1.0.2 and running into issues anywhere I use redux-thunk.

**Comment by skratchdot** [comment]
I get the `.then()` part of my test case shouldn't really work (I was just tweaking one of your examples trying to get a base redux-thunk example working).  I'll try to come up w/ a better test case, and maybe post some example code here.

**Comment by ianhattendorf** [comment]
I'm running into the same issues moving from 0.0.6 -> 1.0.2 with redux-thunk.

From the redux-thunk readme:

_An action creator that returns a function to perform asynchronous dispatch:_

``` js
const INCREMENT_COUNTER = 'INCREMENT_COUNTER';

function increment() {
  return {
    type: INCREMENT_COUNTER
  };
}

function incrementAsync() {
  return dispatch => {
    setTimeout(() => {
      // Yay! Can invoke sync or async actions with `dispatch`
      dispatch(increment());
    }, 1000);
  };
}
```

_An action creator that returns a function to perform conditional dispatch:_

``` js
function incrementIfOdd() {
  return (dispatch, getState) => {
    const { counter } = getState();

    if (counter % 2 === 0) {
      return;
    }

    dispatch(increment());
  };
}
```

Is there support for calling `store.dispatch(incrementAsync())` and `store.dispatch(incrementIfOdd())`?

**Comment by thaggie** [comment]
I'm having this trouble too upgrading from 0.0.6

**Comment by arnaudbenard** [comment]
It looks like it broke in the update. Feel free to make a PR with this line https://github.com/arnaudbenard/redux-mock-store/commit/14842c4423322cc438d0582473483b8caaf5b3a7#diff-1fdf421c05c1140f6d71444ea2b27638L27 back in and some test. I won't be able to push an update this week. Thx for the feedback. :+1:

**Comment by ianhattendorf** [comment]
I played around with it for a few minutes, and it seems that dispatch is just being passed the action object and not a function. If I modify dispatch to return a promise:

``` js
dispatch(action) {
  actions.push(action);

  return Promise.resolve(action);
}
```

then it works for me, but that's only if the thunk returns a promise:

``` js
function incrementAsync() {
  return dispatch => {
    if (someCondition) {
      return dispatch(increment());
    }
    return Promise.resolve();
  };
}
```

I'll take a look at this some more tomorrow.

**Comment by arnaudbenard** [comment]
The promise interface example in the README is just one example that works with actions that return promises. Each action can implement their own logic. If the action returns a promise, then use a promise interface to test it. If the action is a timeout, either promisify it or simply use a timeout to test it (see example below)

``` js
  it('redux-thunk example #1', (done) => {
    const INCREMENT_COUNTER = 'INCREMENT_COUNTER';

    function increment() {
      return {
        type: INCREMENT_COUNTER
      };
    }

    function incrementAsync() {
      return dispatch => {
        setTimeout(() => {
          // Yay! Can invoke sync or async actions with `dispatch`
          dispatch(increment());
        }, 10);
      };
    }

    const store = mockStore({});
    store.dispatch(incrementAsync());

    setTimeout(() => {
      const [action] = store.getActions();

      expect(action.type).toEqual(INCREMENT_COUNTER);
      done();
    }, 10);
  })
```

The second example works already:

``` js
    const store = mockStore({});

    store.dispatch(incrementIfOdd())
    const [action] = store.getActions();

    expect(action.type).toEqual(INCREMENT_COUNTER);
```

Would love some feedback on that!

**Comment by Darmody** [comment]
@arnaudbenard It resolved problem, but use `setTimeout` is not good enough...

**Comment by jacobrask** [comment]
I would not expect `mockStore.dispatch` to return anything different than a regular redux dispatch would. @arnaudbenard's example looks ok.

**Comment by ghost** [comment]
@arnaudbenard, you mentioned in https://github.com/arnaudbenard/redux-mock-store/issues/31#issuecomment-200724663 that the second example already works.

The problem with your test is that you are not using any state to determine if the counter is odd or not.

``` javascript
    const middlewares = [thunk];
    const mockStore = configureStore(middlewares);

    describe('#incrementOdd', () => {
      it ('dispatches INCREMENT when the state is an odd number', () => {
        const store = mockStore(3);
        store.dispatch(actions.incrementOdd());
        expect(store.getActions()).to.include(actions.increment())
      });

      it ("does NOT dispatches INCREMENT when the state is even", () => {
        const store = mockStore(4)
        store.dispatch(actions.incrementOdd());
        expect(store.getActions()).to.not.include(actions.increment());
      });
```

The example above doesn't work, `incrementOdd()` is just receiving `dispatch` and the `getState` is undefined.
