### ISSUE TITLE
Callback called multiple times

### ISSUE THREAD

**Issue by ingro** [reduxjs/redux-mock-store#5]
Hello! I have an issue with failing tests on Mocha.

Given an array of expected actions, if the last one fails Mocha return me the correct wrong expectation, but if another actions fails (before the last), the callback is called multiple times and Mocha return me thi exception: `Error: done() called multiple times`. So I don't know which action failed!

The problem is that the mocked store when catching an exception, pass it as argument to the callback and doesn't throw it, so it keeps running and when it reach the last action, calls the callback again.

I don't know if that's a problem only with Mocha though, in that case maybe it should be configurable to make it work with every testing library.

Here's a simple test to replicate the behaviour:

``` javascript
  it('handles multiple actions', done => {
    const store = mockStore({}, [{ type: 'ADD_ITEM' }, { type: 'REMOVE_ITEM' }], done);

    store.dispatch({ type: 'ADD_ITEMS' });
    store.dispatch({ type: 'REMOVE_ITEM' });
  });
```

**Comment by arnaudbenard** [comment]
Thx for the feedback, I could reproduce the bug. Unfortunately I am pretty busy during the next few days and I'm not gonna be able to submit a fix soon. You are welcome to make a PR and I will review it :)

**Comment by roblafeve** [comment]
I'm experiencing this issue as well.

**Comment by arnaudbenard** [comment]
I have pushed a fix in `v0.0.4`, can you check if it worked?

@roblafeve @ingro

**Comment by roblafeve** [comment]
@arnaudbenard :tada: that worked like a charm! Thanks for the quick turnaround!

**Comment by roblafeve** [comment]
@arnaudbenard however, it does appear that `expect().toEqual()` doesn't perform a deep comparison. It is throwing errors for identical actions in certain cases. To test this I swapped out `expect` with `chai.expect` and used its `eql` method which does a deep comparison and it resolved the problem.

**Comment by ingro** [comment]
Thanks for the fix @arnaudbenard , now it works as expected! :D
@roblafeve can you provide an example of failing actions? Didn't hit that issue on my tests.

**Comment by roblafeve** [comment]
@arnaudbenard @ingro — I've spent some time trying to pinpoint the cause of the issue I was having. My payload object apparently wasn't a primitive (provided via an ajax response). Performing `Object.assign({}, res)` and passing this into my action creator resolves the issue. Not sure how strict that comparison needs to be, but at least that explains why I was having the issue. Not necessarily a bug, but thought you'd be interested to know this can happen. Thanks!
