### ISSUE TITLE
Done not being called if test fail in subscribe callback

### ISSUE THREAD

**Issue by r1cebank** [reduxjs/redux-mock-store#50]
Hi, I tried your examples and I realize mocha is not catching the error thrown if i used subscribe, also the done callback is not being called. Here is what I used to test this. I wonder if I did anything wrong or if I need to do anything extra for mocha to register these errors. Thanks
![screenshot at jun 21 16-58-06](https://cloud.githubusercontent.com/assets/261671/16250331/62faed96-37d1-11e6-958e-ec15b82356e3.png)

**Comment by r1cebank** [comment]
I am using mocha 2.5.3, chai as my assertion library

**Comment by dmitry-zaets** [comment]
Can you please provide the code of your action and test including store preparation?
That would allow us to reproduce case.

**Comment by r1cebank** [comment]
I used test in your test folder

```
it('subscribes to dispatched actions', (done) => {
    const store = mockStore();
    const action = { type: 'ADD_ITEM' };

    store.subscribe(() => {
      expect('s').toEqual('a');
      done();
    });
    store.dispatch(action);
  });
```

so instead of failling the test, the test timeout, later I wrapped this with a try..catch and it worked that way. I wonder if that is the correct way to catch errors in store subscribe:

**Comment by arnaudbenard** [comment]
@r1cebank I ran you test locally and it failed, which version of node are you running?

```
➜  redux-mock-store (master) ✔ npm test

> redux-mock-store@1.1.2 test /Users/arnaudbenard/Programming/redux-mock-store
> mocha --compilers js:babel/register --reporter spec test/*.js



  redux-mock-store
    1) subscribes to dispatched actions


  0 passing (722ms)
  1 failing

  1) redux-mock-store subscribes to dispatched actions:

      Error: Expected 's' to equal 'a'
      + expected - actual

      -s
      +a

      at Object.assert [as default] (node_modules/expect/lib/assert.js:20:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:69:26)
      at Array.<anonymous> (test/index.js:143:19)
      at dispatch (src/index.js:40:25)
      at Object.dispatch (node_modules/redux-thunk/lib/index.js:15:14)
      at Context.<anonymous> (test/index.js:146:11)



npm ERR! Test failed.  See above for more details.
```

**Comment by r1cebank** [comment]
I am using node v6.0.0

**Comment by arnaudbenard** [comment]
@r1cebank I tried with node v6 and it works. You should push your repo with the code. I can't reproduce your error.

**Comment by r1cebank** [comment]
@arnaudbenard Thanks for looking into this, I just discovered this was caused by the way I wrote some part of the code.
