### ISSUE TITLE
index.d.ts wrong version was merged

### ISSUE THREAD

**Issue by brauliodiez** [reduxjs/redux-mock-store#52]
Just realized, 

In this PR we merged the wrong version of the d.ts definitions:

[https://github.com/arnaudbenard/redux-mock-store/issues/39](https://github.com/arnaudbenard/redux-mock-store/issues/39)

The right version was the one commented by @asgarddesigns  but by mistake we merged the one in the PR.

```
import {Store} from 'redux';

interface MockStore extends Store {
    getState():any;
    getActions():Array<any>;
    dispatch(action:any):any;
    clearActions():void;
    subscribe():any;
}

declare function configureStore(...args:any[]):(...args:any[]) => MockStore;
export = configureStore;

```

I have created a new PR containing the right version:

[https://github.com/arnaudbenard/redux-mock-store/pull/51/files](https://github.com/arnaudbenard/redux-mock-store/pull/51/files)

**Comment by thasner** [comment]
can you publish a new release with the corrected typings?

**Comment by arnaudbenard** [comment]
Done!

**Comment by thasner** [comment]
thanks @arnaudbenard !!
