### ISSUE TITLE
Action dispatched in catch statements don't get called.

### ISSUE THREAD

**Issue by fahrradflucht** [reduxjs/redux-mock-store#56]
I created [this Stackoverflow questions](http://stackoverflow.com/questions/38641979/why-does-redux-mock-store-dont-show-an-action-dispatched-in-catch-promises) a few days ago, but I didn't get an answer. I tried since but I didn't find a solution to the problem.

The problem basically occurs when I dispatch actions in catch statements. They neither show up in `store.getActions()` nor is the state altert. I described it in relative detail in the question so I won't repeat it here. Feel free to request more info though.

I'm still not sure if it's a bug or if I'm just doing it wrong.

**Comment by dmitry-zaets** [comment]
@Fahrradflucht Issue is not related to redux-mock-store.
It is related to promise workflow and javascript event loop.
See the [answer](http://stackoverflow.com/questions/38641979/why-does-redux-mock-store-dont-show-an-action-dispatched-in-catch-promises#answer-38706354).
