### ISSUE TITLE
Store's getActions method is returning empty during unit test

### ISSUE THREAD

**Issue by williamcheng7341** [reduxjs/redux-mock-store#60]
I have no idea why this action is array is becoming empty, especially when I log it inside the dispatch action it seems to push it in just fine. Somewhere inside the dispatch of the action it is getting cleared. If anybody has any ideas that would be a great help.

Here is the unit test:

```
let response: any = [{ 'displayOrder': -1, 'formTypeId': 3717, 'id': 829, 'name': 'a', 'parentId': 3717 }];
let prefix: string ='TestString'
it('should call RECEIVE_DATA when fetching has been done', () => {
    nock(someURL)
        .get('someURL')
        .reply(200, response);

    let collection: Array<any> = response;
    const expectedActions = [
        {
            type: prefix + '_RECEIVE_DATA',
            data: Immutable.List<IChildEntity>(collection),
        }
    ]
    const store = mockStore({ MetadataField: [] });
    let id: number = 3717;

    return store.dispatch(IChildEntityActions.initializeData(prefix, id))
        .then(
        () => { // return of async actions
            Chai.expect(store.getActions()).to.deep.equal(expectedActions);
        })
})
```

})

**Comment by williamcheng7341** [comment]
And this is the thunk it is calling:

export function initializeData(type: string, id: number): (dispatch: any, getState: any) => Promise<any> {

```
return function (dispatch: any, getState: any): Promise<any> {
    let data: Immutable.List<IChildEntity>;

    return fetch(constructUrl(parentTypeName, id, childTypeName)).then(
        response => {
            if (response.ok) {
                response.json().then(
                    value => {
                        let collection: Array<any> = value;

                        dispatch(receiveData(type, Immutable.List<any>(collection)));
                    });
            }
        }
    );
};
```

}

receiveData just dispatches an action object

**Comment by dmitry-zaets** [comment]
@williamcheng7341 have you checked that `dispatch(receiveData(type, Immutable.List<any>(collection)));` is actually called in your rest? Simply debug it to ensure that all mock workflow is correct and proper action is dispatched.

**Comment by williamcheng7341** [comment]
I did and it is being called. This is the result of my unit test. The store.getActions returned an empty bracket in the assert, but somehow it is actually comparing the different data. Would this be an async issue? Thanks!

  1) async actions should call RECEIVE_DATA_ICHILDENTITY when fetching todos has been done:

      AssertionError: expected [] to deeply equal [ Array(1) ]
      + expected - actual

                   "formTypeId": 3717
                   "id": 829
                   "name": "a"
                   "parentId": 3717
      -            "unique": "8fb0382d-d2fc-4dfe-9195-34d74e87c529"
      +            "unique": "522dcfcb-eda3-4cec-a90c-b067f5e76070"
                 }
               ]
               "ownerID": [undefined]
             }

**Comment by williamcheng7341** [comment]
Issue was caused by a error which was being swallowed by the return statement.  Thanks for the help!

**Comment by dmitry-zaets** [comment]
@williamcheng7341 always welcome!
