### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by arnaudbenard** [reduxjs/redux-mock-store#62]
A lot of recent PRs introduce changes to the TypeScript definition and it causes problems to users. It would be wiser to defer the support to https://github.com/DefinitelyTyped/DefinitelyTyped and make the package more stable.

Let me know what you think.

**Comment by huy-nguyen** [comment]
If you want to leave maintenance of the type definition to the community, you should remove the `index.d.ts` file from the repo because TypeScript looks for that file first before looking for type definitions elsewhere.
