### ISSUE TITLE
TypeError: mockStore is not a function

### ISSUE THREAD

**Issue by Antho2407** [reduxjs/redux-mock-store#66]
Hey there ! I'm getting an issue with the library (i'm using Jest). Here is the code : 

```
import * as actions from '../actions'
import configureMockStore from 'redux-mock-store'
import thunk from 'redux-thunk'

const middlewares = [thunk]
const mockStore = configureMockStore(middlewares)

describe('Dataset actions', () => {
    it('compareMutuallyExclusiveKeys - default parameters', () => {
        const expectedActions = [{
            type: actions.COMPARE_MUTUALLY_EXCLUSIVE_KEYS,
            payload: {
                mutually_exclusive_keys: [],
                meta: {}
            }
        }]
        const store = mockStore({})
        return store.dispatch(actions.compareMutuallyExclusiveKeys())
            .then(() => {
                expect(store.getActions()).toEqual(expectedActions)
            })
    })
})
```

And the error : 

```
TypeError: mockStore is not a function
```

Tried to upgrade redux-thunk (2.0.1) and redux-mock-store (1.1.4), but still getting the error...
Thanks for your help !

**Comment by hanford** [comment]
I'm seeing this too with even simpler code --> 

``` js
import configureStore from 'redux-mock-store'
import thunk from 'redux-thunk'

const middlewares = [thunk]
const mockStore = configureStore(middlewares)
const store = mockStore({})

console.log(store)

it('should be true', () => expect(true).toEqual(true))
```

![](http://d.pr/i/KEn8+)

Using `redux-thunk: 2.1.0` and `redux-mock-store: 1.1.4`

**Comment by hanford** [comment]
@Antho2407 Looks like the solution for me was to `jest.unmock` things.

This is working for me 

``` js
jest.unmock('./index.js')
jest.unmock('redux-mock-store')
jest.unmock('redux-thunk')

import configureStore from 'redux-mock-store'
import thunk from 'redux-thunk'
import t from './actionTypes'

const middlewares = [thunk]
const mockStore = configureStore(middlewares)

it('should dispatch action', () => {
  const initialState = {
    notes: ''
  }

  const addNote = { type: t.SET_CHECKOUT_NOTES, notes: 'JACK!' }

  const store = mockStore(initialState)
  store.dispatch(addNote)

  const actions = store.getActions()

  expect(actions).toEqual([addNote])
})
```

**Comment by Antho2407** [comment]
@hanford Also had to unmock my `actions.js` file, then your solution worked perfectly, thanks for the help !

**Comment by dmitry-zaets** [comment]
You need to unmock all real dependencies:

> In order to write an effective unit test, you want to be able to isolate a unit of code and test only that unit – nothing else. It is fairly common and good practice to consider a module such a unit, and this is where Jest excels. Jest makes isolating a module from its dependencies extremely easy by automatically generating mocks for each of the module's dependencies and providing those mocks (rather than the real dependency modules) by default.

https://facebook.github.io/jest/docs/automatic-mocking.html
