### ISSUE TITLE
Typescript definition removal not published?

### ISSUE THREAD

**Issue by brauliodiez** [reduxjs/redux-mock-store#70]
Hi,

  I'm getting some errors when transpiling the project, just checked the repository and found that you have removed the d.ts file and recommend using the typings one:

https://github.com/arnaudbenard/redux-mock-store/commit/9e1d0143056eb0279abd71576c39ffcebc18943e

But if I just go via npm install I can see that the .d.ts is still on the local files installed, Is there a new version pending to be published on npm?

Thanks

**Comment by arnaudbenard** [comment]
@brauliodiez I published a new version just now, let me know if it works.

**Comment by brauliodiez** [comment]
Tried the new version and works fine. Just only one strange thing (I'm running on windows), I got an error when installing and had to run:

npm install redux-mock-store --save-dev --no-optional

Withouth the no-optional it throws an error.

**Comment by dmitry-zaets** [comment]
Which kind of error it throws?

**Comment by brauliodiez** [comment]
Hi just wiped node_modules and tried from a clean cut, now I'm getting a warning instead of error:

![warning](https://cloud.githubusercontent.com/assets/1457912/18283543/0ef69cfa-7466-11e6-8718-6d7b05372694.png)

Sorry donno what happen to get that as an error instead of a warning.
