### ISSUE TITLE
Mock Store State is not being updated

### ISSUE THREAD

**Issue by adamyonk** [reduxjs/redux-mock-store#71]
I'm having the same issue as #45. Maybe I'm not understanding this correctly, but does mock-store actually run the actions through the reducers anywhere? I'm not seeing how they're ever connected with a setup like this:

``` javascript
import configureStore from 'redux-mock-store'
import thunk from 'redux-thunk'
const mockStore = configureStore([thunk])
const store = mockStore({ ...state })
console.log(store.getState()) // => { ...state }
store.dispatch(someAction())
console.log(store.getActions()) // => [ someAction() ] The action does show up here!
console.log(store.getState()) // => { ...state } But this is the same unchanged state as above
```

**Comment by dmitry-zaets** [comment]
As you can see from [codebase](https://github.com/arnaudbenard/redux-mock-store/blob/master/src/index.js#L36) - it doesn't execute any reducers.
it even doesn't accept any of them during setup.
It only notifies the list of subscribers.
So the state will be always the same.

**Comment by adamyonk** [comment]
OK, that's what I was thinking. Is there a reason for `getState` in the API then?

**Comment by dmitry-zaets** [comment]
I'm not sure, but I think the main reason is backward compatibility with redux API.
As you can see [here](https://github.com/arnaudbenard/redux-mock-store/blob/master/src/index.js#L13) - the value of getStore is just bypassed.

**Comment by adamyonk** [comment]
Ah, OK. So I was thinking that I'd be able to test the state along with testing what actions were triggered, but `redux-mock-store` is really _just_ for the actions part. Seeing `getState` it in the docs threw me, thanks for clarifying!

**Comment by adamyonk** [comment]
The one place this kind of falls down is when you're testing something that uses an async action creator (thunks), that change the state before triggering other actions.

**Comment by dmitry-zaets** [comment]
Yep, `redux-mock-store` is just for the testing actions part. To test reducer and it states you don't need any kind of mock. You just need to test reducer as a pure function (Input -> Output), that's all.

**Comment by dmitry-zaets** [comment]
For testing, complex flows with async actions you can check https://github.com/redux-things/redux-actions-assertions, it was designed for that kind of testing.

**Comment by adamyonk** [comment]
That is _exactly_ what I needed. Thanks, @dmitry-zaets!

**Comment by dmitry-zaets** [comment]
Always welcome!

**Comment by jhalborg** [comment]
God damnit, I just found this after pulling my hair for two hours. I think it should be added to the docs very explicitly that the mock stores' state is never changed, as one would assume it does when it's in the API. Reading the discussion here, it does make sense, but it's potentially a timewaster

**Comment by ohtangza** [comment]
This is definitely something that should have documented in README.md.

@dmitry-zaets Can I document it and make a pull request not to confuse the newbie here?

**Comment by dmitry-zaets** [comment]
@ohtangza Sure, would be happy to merge the PR

**Comment by pzhine** [comment]
Testing your reducer alongside your actions with redux-mock-store is as simple as running your reducer function on the state that you pass to the mock store and the action you expect:

```es6
import actions from './actions'
import reducer from './reducer'
import initialState from './initialState'

const state = { ...initialState, numbers: '23' }
const expectedAction = { type: 'DELETE_LAST_NUMBER', payload: '*' }
return store.dispatch(actions.pressKey('*')).then(() => {
  expect(store.getActions()[0]).toEqual(expectedAction)
  expect(reducer(state, expectedAction)).toEqual({ ...state, numbers: '2' })
})
```

**Comment by tutts** [comment]
I had the same issue, and found I kept writing the same lines over and over to test store, so wrote a tiny lib on top of redux-mock-store to capture snapshots of reducer states [here](https://github.com/tutts/redux-state-snapshot)

**Comment by mbellman** [comment]
Incidentally, this can be achieved using the following:

```
import configureMockStore from 'redux-mock-store';
import appReducer from 'path/to/your/appReducer';

const createMockStore = configureMockStore(...);

const createState = initialState => actions => {
  return actions.reduce((acc, action) => appReducer(acc, action), initialState);
};

...

it('...', () => {
  const state = createState({ ... } );
  const store = createMockStore(state);

  store.dispatch(...);

  // Assert as you prefer
  expect(store.getState()).toEqual(...);
  expect(store.getState()).toMatchObject(...);
  expect(store.getActions()).toEqual([ ... ]);
});
```

This helps in particular if you're dispatching thunks which rely on `getState()` to control their behavior, or otherwise need `getState()` to reflect changes. This approach still causes the initial state to be "fast-forwarded" based on the dispatched action lineup any time `getState()` is called, so bear that in mind.

**Comment by mbellman** [comment]
Incidentally, this can be achieved via the following:

```
import configureMockStore from 'redux-mock-store';
import appReducer from 'path/to/your/appReducer';

const createMockStore = configureMockStore([ ... ]);

const createState = initialState => actions => actions.reduce(appReducer, initialState);

...

it('...', () => {
  const initialState = createState({ ... } );
  const store = createMockStore(initialState);

  store.dispatch(...);

  // Assert as you prefer
  expect(store.getState()).toEqual(...);
  expect(store.getState()).toMatchObject(...);
  expect(store.getActions()).toEqual([ ... ]);
});
```

This is particularly useful if you're dispatching thunks which rely on `getState()` to control their behavior. It's also suspiciously close to just using your _real_ store and testing dispatches against that, although you can still customize the initial state and check dispatched actions more easily.

**Comment by JohnDDuncanIII** [comment]
Modified version of pzhine's answer that supports Immutable and calling the same action creator multiple times in a different action creator (we have an async action creator that we pass a synchronous action creator to).

```js
import { fromJS } from "immutable"
import mockStore from "__tests__helpers/mockStore"

import { setTranscriptsValues } from "shared/profiles/event/event-profile-action-creators"
import { eventReducer } from "shared/profiles/event/event-profile-reducer"

let store = mockStore({})

const setTranscriptsValuesHelper = ({
    values,
    profileId,
}) => {
    store = mockStore(
        eventReducer(
            fromJS(store.getState()),
            setTranscriptsValues({
                values,
                profileId,
            })
        )
    )
}

beforeEach(() => {
    store = mockStore({})
})

it("loadInlines", () => {
    loadInlines({
 		...stuff
        setTranscriptsValues: setTranscriptsValuesHelper,
    }).then(() => {
        console.log(store.getState())
    })
})
```

**Comment by agolendukhin** [comment]
@mbellman thanks man! It just works fine.

**Comment by ilguzin** [comment]
Hi guys,

the below is for those who's struggling with Redux-connected components testing, hope this will save you some time:

```javascript
import React from 'react';
import Redux, { AnyAction } from 'redux';
import { Provider } from 'react-redux';
import renderer from 'react-test-renderer';
import createMockStore, { MockStoreEnhanced } from 'redux-mock-store';
import thunk from 'redux-thunk';
import { Input } from 'reactstrap';

const mockStore = createMockStore<State, {}>([thunk]);

interface State {
  dataSourceEdit: DataSourceEditState;
}

// https://github.com/facebook/react/issues/11565#issuecomment-573517172
jest.mock('react-dom', () => {
  const original = jest.requireActual('react-dom');
  return {
    ...original,
    createPortal: (node: any) => node,
  };
});

describe('React-Redux components tests', () => {
  describe('<DataSourceEditor />', () => {
    const initialState: State = {
      dataSourceEdit: {
        dataSource: {
          ...
        },
      },
    };

    // Configure store with real reducers enabled!
    const store = mockStore((actions: Redux.AnyAction[]) => actions.reduce((memo, action: AnyAction) => ({
      ...memo,
      dataSourceEdit: dataSourceEditReducer(memo.dataSourceEdit, action as DataSourceEditingActionObject),
    }), initialState));

    const element = (s: MockStoreEnhanced<State, {}>) => <Provider store={s}><DataSourceEditor /></Provider>;

    let component = renderer.create(element(store));

    const inputLookup = (id: string) => component.root.find(e => e.type === Input && e.props.id === id);

    describe('Name input field editing', () => {
      const newDataSourceName = `${DATA_SOURCE_NAME} after edit`;

      // Important! There is no automatic rendering, we must force it if we expect the changes in test case.
      beforeEach(() => component = renderer.create(element(store)));

      it('should change corresponding state', () => {
        // 1. Check the storage
        expect(store.getState()).toHaveProperty('dataSourceEdit.dataSource.name', DATA_SOURCE_NAME);
        renderer.act(() => {
          // 2. Simulate input field change
          inputLookup('name').props.onChange({ target: { value: newDataSourceName } });
        });
        // 3. Expect the changes to be stored
        expect(store.getState()).toHaveProperty('dataSourceEdit.dataSource.name', newDataSourceName);
      });

      it('should update input field value', () => {
        // 4. Expect the changes to be rendered
        expect(inputLookup('name')).toHaveProperty('props.value', newDataSourceName);
      });
    });
  });
});
```

**Comment by AlejandroSilva** [comment]
I finally get to test the final store state like this: 
```
const actions = [ {type: 'action1, payload: 1}, {type: 'action2, payload: 2}]
const finalState = actions.reduce(myCoolReducer, INITIAL_STATE)
const expectedState = {...}
expect(expectedState).toEqual(finalState)
```
The reducer is a pure function, so in order to get the final state we just has to call every action on top of an initial state. This way every action receive the previous state and return a new one until the end of the array.
