### ISSUE TITLE
Testing nested promises

### ISSUE THREAD

**Issue by gregdymek** [reduxjs/redux-mock-store#79]
Hi,
I'm wondering if it's possible to test nested promises:
eg. response.json() - it's a promise which can be invoked after fetch promise,
however if I create "then" method for "store.dispatch" the nested promise won't get executed, is it possible to wait until it's executed?
Regards

**Comment by dmitry-zaets** [comment]
Hi,
Can you please provide a code example?

**Comment by gregdymek** [comment]
Hi.
Let's say our rest webservice returns 400 status with json validation errors where there are some,
but when there are no errors it returns 201 code with Location header - with no json body (as it's defined in Rest).
In that case we need to manually transform the error to json using response.json().
Here is the sample:

```javascript
return fetch(...).catch(error => {
      const status = error.response ? error.response.status : 500;
      if (status === 400) {
        error.response.json().then(responseJson => {
          dispatch(validationErrorsAction(responseJson));
        });
      }
    });
```
Even when I return this error.response.json() predicate it's too late, this validationErrorsAction won't be reflected.
There won't be a problem if the rest service returns json body (I did it that way so we transform to json in "then" predicate before dispatching the action), and it's working with your plugin then.
How would you solve when there is no json body?
Regards

**Comment by dmitry-zaets** [comment]
To make the full workflow works properly and wait till the end of last action you need to add couple of return statements:

```javascript
return fetch(...).catch(error => {
   const status = error.response ? error.response.status : 500;
   if (status === 400) {
     // this call will return promise, so in order to wait until it finishes - you need to return it.
     return error.response.json().then(responseJson => {
         // if validationErrorsAction is async and returns a promise - you should also return here
         // dispatch(validationErrorsAction(responseJson));
         return dispatch(validationErrorsAction(responseJson));
     });
   }
 });

```

**Comment by gregdymek** [comment]
I think I tried it that way, and it only reflected 1st fetch promise,
when I ran the code which looked like the one you sent in karma debug mode, it was ok,
but when I ran it in a single run it was failing, so I guess those nested promises are ignored - especially in catch block - in then it would probably work fine (and I think debug mode was slowing down test execution so nested promises got executed). What do you think?

**Comment by dmitry-zaets** [comment]
Would be nice if you will be able to share an example  setup so we can reproduce it. (Setup, code and test.)

**Comment by dougajmcdonald** [comment]
I think I have a similar issue. I should be able to provide some code snippets:
**Action:**
```
export const requestData = () => (dispatch, getState, api) => {

  const url = '/data-url';

  return dispatch({
    type: 'MAP/REQUEST_DATA',
    payload: api.localFetch(url)
  }).then((status) => {
    return dispatch({ type: 'MAP/SET_LOADING_STATUS', status );
  }).catch(() => {});
};
```

If I write a test which tries to check that the `setLoadingStatus` action was dispatched like this:

```
     it('calls x_PENDING and x_FULFILLED when valid data is returned', () => {

      const expectedActions = [
        { type: 'MAP/REQUEST_DATA_PENDING' },
        { type: 'MAP/REQUEST_DATA_FULFILLED', payload: payload },
        { type: 'MAP/SET_LOADING_STATUS'  }
      ];

      const store = mockStore(initialState);

      return store.dispatch(actions.requestPointData(location))
        .then(() => {
          expect(store.getActions()[0].type).to.deep.equal(expectedActions[0].type);
          expect(store.getActions()[1].type).to.deep.equal(expectedActions[1].type);
          expect(store.getActions()[2].type).to.deep.equal(expectedActions[2].type);
        });
    });
```
The first two actions are fine and the third action never appears in `store.getActions()`.

**Comment by dmitry-zaets** [comment]
@dougajmcdonald 
Thanks for posting a comment,
Can you please specify where is your third action?
Also, can you please show implementation of`api.localFetch(url)`? Isn't it async?

**Comment by dougajmcdonald** [comment]
@dmitry-zaets my third action is the `setLoadingStatus()` function.

I edited it in my comment above so it's more obvious. (It's the `return dispatch({ type: 'MAP/SET_LOADING_STATUS', status );` bit)

My `localFetch` function looks like this:

```
localFetch(url, options) {
    return fetch(`some_url`, options)
      .then(this.checkStatus)
      .then(this.parseJSON);
}
```

The `checkStatus` and `parseJSON` are just wrappers for simple stuff like error checking and returning `response.json()`

**Comment by dmitry-zaets** [comment]
I'm sorry but  `payload: api.localFetch(url)` this is part synchronizing your code, which means that payload will not contain a value, but just a promise, and result of localFetch will be lost in the async flow.

**Comment by dmitry-zaets** [comment]
Should be something like this:
```js
export const requestData = () => (dispatch, getState, api) => {
  const url = '/data-url';
  return api.localFetch(url).then((payload)=> {
    return dispatch({
      type: 'MAP/REQUEST_DATA',
      payload: payload
    }).then((status) => {
      return dispatch({ type: 'MAP/SET_LOADING_STATUS', status );
    }).catch(() => {});
  });
};
```

**Comment by dougajmcdonald** [comment]
@dmitry-zaets Yeah I see what you mean, I'm using `redux-promise-middleware` which requires me to dispatch an action with the async work as the payload:
https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/introduction.md

The middleware then dispatches actions `_PENDING` and then `_FULFILLED` or `_REJECTED` when the result of that promise resolves.

Is there a way I can use `redux-mock-store` with this pattern? or am I stuck?

**Comment by dmitry-zaets** [comment]
Hm, should be fine, if you register the middleware.
Would you be able to share the working example? This will allow us to reproduce it and help you.
Thanks a lot!

**Comment by daiict218** [comment]
Hi,
My code seems like 

```
//from my component
const someFunc = async ({arg1, arg2...}) => {
    await dispatch(setWithSomePromise({arg1, arg2}));
    // setWithSomePromise is a promise 
}

//in my actions file, I've done
const setWithSomePromise = ({arg1, arg2}) => async dispatch => {
    const someOtherPromiseResp = await(someOtherPromise);

    dispatch({
        type: 'MY_ACTION',
        payload: someOtherPromiseResp,
    });

    return someOtherPromiseResp;
}
```

In my `spec` file, I've registered `thunk` as middleware with `redux-mock-store` and it is working fine as well but not in this case. It gives me error as : 
` Error: Actions may not have an undefined "type" property. Have you misspelled a constant? Action: {}`

Can someone help me rectifying this error?
