### ISSUE TITLE
we need to promise (or callback) after dispatch

### ISSUE THREAD

**Issue by shallwefootball** [reduxjs/redux-mock-store#83]
i have test with nock.js

i don't want to use `setTimeout`

is there anything else?

**Comment by dmitry-zaets** [comment]
Thanks for creating the issue.

Here is the documentation and the basic example for testing with nock.js: http://redux.js.org/docs/recipes/WritingTests.html#async-action-creators

In order to give you relevant answer, we would like to get a bit more explanations
and the code sample.

**Comment by dmitry-zaets** [comment]
Please, reopen issue if needed.
