### ISSUE TITLE
Add a link in the readme for chai binding?

### ISSUE THREAD

**Issue by themouette** [reduxjs/redux-mock-store#87]
Hi,

I created [simple chai bindings](https://github.com/themouette/chai-redux-mock-store) to test redux-store, should I open a MR to add a link to the README?

Thanks for your great work by the way :)

**Comment by dmitry-zaets** [comment]
You can check out also another version of chai bindings: https://redux-things.github.io/redux-actions-assertions/chai.html

**Comment by themouette** [comment]
How can I have missed it!

Sorry for the duplicate.
