### ISSUE TITLE
Error: cannot find babel preset

### ISSUE THREAD

**Issue by thurt** [reduxjs/redux-mock-store#89]
we are using redux-mock-store in a react native project and we are running into this issue:

![cannotfindpreset](https://cloud.githubusercontent.com/assets/8955144/23075753/a9cb128a-f50b-11e6-8148-f2547ed86f53.png)

we are not using `babel-preset-es2015` in our project, but we must install it in order to make this error go away. 

Possible cause: I have looked at the `package.json` file for this package and noticed all the dependencies are listed as devDependencies -- as far as I know , devDependencies for third party modules do not get installed. Additionally, the error message suggests babel is looking for files relative to node_modules/redux-mock-store first. A possible fix would be to list babel-preset-es2015 as a regular dependency instead of a devDependency.

**Comment by arnaudbenard** [comment]
@thurt Babel is used in the `prepublish` phase to produce an ES5 compatible output. Did you manage to find a fix for your problem?

**Comment by cesarp** [comment]
This happened to me with another library
https://github.com/maslianok/react-resize-detector/pull/8

It happens because .babelrc is included in the published package and Jest tries to process it with babel, you can ignore it in the jest configuration or even better not to publish the .babelrc file.
