### ISSUE TITLE
'exports is not defined' error -> add a vanilla-compatible version?

### ISSUE THREAD

**Issue by pdesjardins90** [reduxjs/redux-mock-store#90]
I don't use commonJS or webpack. (I'm in a polymer-redux 1.X project)

I've tried adding this mock-store to my tests but I get a 'exports is not defined' error when running my tests. 

Could you possibly add a vanilla version of this file in the release?

**Comment by arnaudbenard** [comment]
There's a vanilla version that gets compiled during the `prepublish` step. How do you require the library?

**Comment by pdesjardins90** [comment]
Well just another version of the file next to the existing one in the dist folder would be just fine I guess, thanks!

**Comment by dmitry-zaets** [comment]
@pdesjardins90 can you please test build of this pr? #108

**Comment by pdesjardins90** [comment]
I'll check this out within the next week!

**Comment by pdesjardins90** [comment]
Ok that assuredly fell between two chairs, but I finally came around to testing it.
Good news is that it works.

@arnaudbenard I just ran yarn build and it generated the UMD build seamlessly, you can try it without any knowledge of UMD like me

**Comment by sbason** [comment]
@pdesjardins90 Is it possible to get this merged? Would be really good to get a CommonJS version.

**Comment by pdesjardins90** [comment]
I have no push access to this repo, I just filed the issue!

**Comment by pdesjardins90** [comment]
@dmitry-zaets, can you merge [this](https://github.com/arnaudbenard/redux-mock-store/pull/108) please?

**Comment by arnaudbenard** [comment]
@pdesjardins90  @sbason I've merged the PR to master but it broke the installation process (I had to revert it). Like I mentioned in the PR, I'm not an expert in CommonJS build and even less in Rollup. If we want this PR merged, the whole build process needs to work (https://circleci.com/gh/arnaudbenard/redux-mock-store/137)
