### ISSUE TITLE
arnaudbenard.com has expired, the documentation can't be accessed

### ISSUE THREAD

**Issue by sampi** [reduxjs/redux-mock-store#96]
When trying to view the documentation at http://arnaudbenard.com/redux-mock-store/ 
I see a `Domain Expred` message instead of the documentation.

Please fix this or move the docs to GitHub Pages/Wiki so it's always available with the code =)

**Comment by arnaudbenard** [comment]
Done sorry about that! Thank you for the reminder

**Comment by sampi** [comment]
Nice one. I'm closing this issue.

Thanks!
