### ISSUE TITLE
Docs - Invoke action when passed to the store dispatcher

### ISSUE THREAD

**Issue by john-d-pelingo** [reduxjs/redux-mock-store#98]
Thank you for this really helpful utility library.

This is probably a minor typo but at the [docs](http://arnaudbenard.com/redux-mock-store/) at the synchronous action section
```javascript
// Dispatch the action
store.dispatch(addTodo)
```
shouldn't the action creator be invoked when passed to the dispatcher?

It had me confused for a bit when I was implementing it to my project.

**Comment by arnaudbenard** [comment]
You are right, thank you for discovering this! Can you make a PR on `gh-pages`? 
https://github.com/arnaudbenard/redux-mock-store/tree/gh-pages
